{% set name = "apache-airflow-providers-databricks" %}
{% set version = "6.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_databricks-{{ version }}.tar.gz
  sha256: 43da6aae7acc80e47f95706619d2b9fadbe9fd432e6a852930a96d9c6c254a81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - mergedeep >=1.3.4
    - pyarrow >=14.0.1
    - python >=3.8
    - aiohttp >=3.9.2,<4
    - apache-airflow-providers-common-sql >=1.10.0
    - apache-airflow >=2.7.0
    - databricks-sql-connector >=2.0.0,<3.0.0,!=2.9.0
    - requests >=2.27.0,<3

test:
  imports:
    - airflow.providers.databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-databricks for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/databricks/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
