{% set name = "apache-airflow-providers-databricks" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-databricks-{{ version }}.tar.gz
  sha256: b6bc17f3c6de9bea4e2c656dabf192190282a03ae5a211e7af5213f7be3e4000

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.6.3,<4
    - apache-airflow-providers-common-sql >=1.5.0
    - apache-airflow >=2.4.0
    - databricks-sql-connector >=2.0.0,<3.0.0
    - requests >=2.27,<3

test:
  imports:
    - airflow.providers.databricks
    - airflow.providers.databricks.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-databricks package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
