{% set name = "apache-airflow-providers-databricks" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-databricks-{{ version }}.tar.gz
  sha256: 38b2eede39ea50bd2601935e0c5bf128f56c2e67757bd292806649b06ed802ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - aiohttp >=3.6.3,<4
    - apache-airflow-providers-common-sql >=1.2.0
    - apache-airflow >=2.2.0
    - databricks-sql-connector >=2.0.0,<3.0.0
    - requests >=2.27,<3

test:
  imports:
    - airflow.providers.databricks
    - airflow.providers.databricks.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-databricks package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
