{% set name = "apache-airflow-providers-databricks" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_databricks-{{ version }}.tar.gz
  sha256: 848a4782367f83730e3b38a46203d0f134aa90b6f851d280ef56841b05990e0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.6.3,<4
    - apache-airflow-providers-common-sql >=1.10.0
    - apache-airflow >=2.6.0
    - databricks-sql-connector >=2.0.0,<3.0.0,!=2.9.0
    - requests >=2.27,<3

    # picking up some older apache-airflow that allow pendulum 3, which doesn't work
    # (these should ideally be patched)
    - pendulum <3.0.0

test:
  imports:
    - airflow.providers.databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-databricks for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/databricks/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
