context:
  name: apache-airflow-providers-databricks
  version: "7.8.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_databricks-${{ version }}.tar.gz
  sha256: ddc33356d6d96917fa32a2ed3ed32fb9ca70906726cadf3d3baca91644750e75

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - apache-airflow-providers-common-sql >=1.27.0
    - requests >=2.32.0,<3
    - databricks-sql-connector >=4.0.0
    - databricks-sqlalchemy >=1.0.2
    - aiohttp >=3.9.2,<4
    - mergedeep >=1.3.4
    # more restrictive for python >=3.13
    - pandas >=2.2.3
    # more restrictive for python >=3.13
    - pyarrow >=18.0.0

tests:
  - python:
      imports:
      - airflow.providers.databricks
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-databricks for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-databricks/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
